development:
  adapter: postgresql
  encoding: unicode
  database: zuykov
  pool: 5
  username: zuykov
  password: eqwe3s_sd3kic

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zuykov
  pool: 5
  username: zuykov_development
  password: 87o4243yqhwboe56w43